// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPb5s3NEZSKByU1XT24vupOhh7MhtiwQo',
    appId: '1:556962988548:web:d413e7b89a8392cdd46b51',
    messagingSenderId: '556962988548',
    projectId: 'flutter-utility-2',
    authDomain: 'flutter-utility-2.firebaseapp.com',
    storageBucket: 'flutter-utility-2.appspot.com',
    measurementId: 'G-Y62X9CEERN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN9zGrvdqfTVmd45em0XqxbPI_grq90lc',
    appId: '1:556962988548:android:04b646c1f75ba9edd46b51',
    messagingSenderId: '556962988548',
    projectId: 'flutter-utility-2',
    storageBucket: 'flutter-utility-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwSiBUGeFQ7pE4Lf8w-jokyT-10RXydIE',
    appId: '1:556962988548:ios:24a3388cf560e1dad46b51',
    messagingSenderId: '556962988548',
    projectId: 'flutter-utility-2',
    storageBucket: 'flutter-utility-2.appspot.com',
    iosBundleId: 'com.example.flutterUtility2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwSiBUGeFQ7pE4Lf8w-jokyT-10RXydIE',
    appId: '1:556962988548:ios:24a3388cf560e1dad46b51',
    messagingSenderId: '556962988548',
    projectId: 'flutter-utility-2',
    storageBucket: 'flutter-utility-2.appspot.com',
    iosBundleId: 'com.example.flutterUtility2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPb5s3NEZSKByU1XT24vupOhh7MhtiwQo',
    appId: '1:556962988548:web:a00563338d897cb5d46b51',
    messagingSenderId: '556962988548',
    projectId: 'flutter-utility-2',
    authDomain: 'flutter-utility-2.firebaseapp.com',
    storageBucket: 'flutter-utility-2.appspot.com',
    measurementId: 'G-C63NR6TCNT',
  );
}
